url: "https://pleunalferink.github.io"
baseurl: "/portfolio"

# Site settings
title: Pleun's
email: nuelp28@gmail.com
description: "Pleun's portfolio website"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/pleun-alferink-921253159/
  - title: instagram
    url: https://www.instagram.com/pleun.nl/
  - title: github
    url: https://github.com/Plok98


# Build settings
markdown: kramdown
permalink: pretty
